### PR TITLE
Concurrency

### PR DESCRIPTION
**Pull request by blundell89**
@sakisk @Jay2Base @terrawheat  @karen-arden 

Readme to be updated and a couple more tests to come

### CODE REVIEW

**Comment by phatboyg** [comment]
@kevbite Lee turned me on to this, and I'd like to merge this into the main code repository: https://github.com/MassTransit/MassTransit/pull/485

**Comment by kevbite** [comment]
Hey @phatboyg that's totally fine, would be great if we could be put on to some contribution list. If you need any help with it, just give us a shout!

**Comment by phatboyg** [comment]
I'll likely merge the commits into the project today. Once that's ready, I'd welcome any pull requests as you resolve issues, etc. The work so far (I took from the concurrency branch) looks great.

I'll add that using the .UseInMemoryOutbox() would likely be helpful here so that the saga is persisted before the events are sent to the broker. That way, a version conflict wouldn't send duplicate events.

```
endpoint.UseRetry(...);
endpoint.UseInMemoryOutbox();
endpoint.StateMachineSaga(_machine, _mongoRepository);
```

This way, the retry policy would retry in case of a version conflict, and the outbox would buffer any send/publishes until a successful completion of the saga occurs.

**Comment by phatboyg** [comment]
FYI, the latest commits, including attribution are here:

https://github.com/phatboyg/MassTransit/blob/mongodb/src/Persistence/MassTransit.MongoDbIntegration/readme.md

**Pull request merged**
